apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  selector:
    app: order-payment
  ports:
    - name: payment-port
      port: 10080
      targetPort: 10080